### ISSUE TITLE
Sections don't filter 

### ISSUE THREAD

**Issue by andrwsalcdo** [olayinkaos/vuejs-news#1]
![image](https://cloud.githubusercontent.com/assets/23638863/26758687/9148eec0-48b3-11e7-81f3-68bac91e06e0.png)

that's what i get when I try to filter. 

in app.js, vm.data.section = 'home', so could that be a reason that it won't properly filter? 

shouldn't there be computed property for a filterSections() or something to that effect? 

I'm learning, so go easy on me.  Thanks for your time.

**Comment by olayinkaos** [comment]
Hi @andrwsalcdo 
Did you replace the NYTimes key in `config.js`? You need to do this to be able to fetch data from the API.
Follow the steps in the [Readme](https://github.com/olayinkaos/vuejs-news/blob/master/readme.md) for clarity. :)
You can also refer to [this section in the tutorial](https://www.sitepoint.com/fetching-data-third-party-api-vue-axios/#implementingcategoryfilters) on how filtering in the app works.

**Comment by andrwsalcdo** [comment]
hi @olayinkaos, 

I found the problem!!! yay. But, it wasn't anything to do with the API key, vm.data.section, or getPosts(). 

don't laugh, but I had a typo in vm.data.sections with the split method. I wrote `.split(',')` rather than the correct way `.split(', ')`.

So, yea, sorry about that. But thank you for the help. It was a great article/tutorial. keep it up 😄

**Comment by olayinkaos** [comment]
Great @andrwsalcdo !
Thank you. Don't hesitate to give a shout if any other issue comes up 😉
